import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Navkar Academy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="w-full h-[3px] bg-black/10 rounded-full my-4 hidden md:block" />
        {children}
        <div className="w-full h-[3px] bg-black/10 rounded-full my-4" />
        <Footer />
      </body>
    </html>
  );
}
